# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Haven Kim
tagline:          'Junior Developer'
description:      'Jekyll blog of strange developer, Haven Kim. Usign Hyde theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'    
baseurl:          https://raacker.github.io/

author:
  name:           'Haven Kim'
  url:            https://

# Use Paginate
paginate:         5
paginate_path:    '/blog/page:num'
gems:             [jekyll-paginate]

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/raacker

LinkedIn:
  addr:           https://kr.linkedin.com/in/heongyeom-kim-633650113


# Atom Setting
atom:
  buildCommand:
    - jekyll
    - build
    - --option
    - --this
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _drafts
