# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            Haven Kim
tagline:          'Junior Developer'
description:      'Jekyll blog of strange developer, Haven Kim. Usign Hyde theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              
baseurl:          /

author:
  name:           'Haven Kim'
  url:            https://

paginate:         5

# Custom vars
version:          1.0.0

Python:           /_post/python

github:
  repo:           https://github.com/raacker
